name: Deploy

concurrency: Deployment

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
          cache: "npm"
      - name: validate github workflow files
        uses: digitalservice4germany/github-actions/github-actions-linter@1cb8bd8ff785c63b2cf13c2fe63241245a8ac7ef
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Install gems
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: npm install
      - name: Build page
        run: npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
        with:
          target_branch: gh-pages
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
